### ISSUE TITLE
"image already liked. Skipping it. 0 liked images so far."

### ISSUE THREAD

**Issue by yuxelmurat** [GabrielDan92/Instagram-Like-Bot#1]
I did all settings and it started to work.

it search and find my tags, open an image but cant like. it says "image already liked. Skipping it. 0 liked images so far." 1 billion times.

**Comment by GabrielDan92** [comment]
Hi Yuxel, that's a fair point. On line 112 you will see the if statement that checks the HTML attribute of the heart button ("if value == "Like").

If your Instagram platform is not in English, then the if statement will not work as expected. Try to go in your browser developer tools (F12 for Google Chrome) and find out what is the "Like" equivalent in your language that Instagram has for that button, and replace it on line 112.

Let me know if you encounter any other issues.
